apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "app-ingress"
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  rules:
    - host: ${TRAEFIK_HOSTNAME}
      http:
        paths:
          - path: /
            backend:
              serviceName: app-service
              servicePort: 80
    - host: "*.${TRAEFIK_HOSTNAME}"
      http:
        paths:
          - path: /
            backend:
              serviceName: app-service
              servicePort: 80
