apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: app-cert
  namespace: ${NAMESPACE}
spec:
  commonName: ${TRAEFIK_HOSTNAME}
  secretName: app-cert
  dnsNames:
    - ${TRAEFIK_HOSTNAME}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
