apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "mailhog-ingress"
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  rules:
    - host: mail-${TRAEFIK_HOSTNAME}
      http:
        paths:
          - path: /
            backend:
              serviceName: "mailhog-service"
              servicePort: 80
