apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
  namespace: ${NAMESPACE}
  labels:
    app: mailhog-service
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8025
    - protocol: TCP
      name: smtp
      port: 1025
  selector:
    app: mailhog
